- hosts: 192.168.29.206
  tasks:
   -  file:
        state: directory
        path: /dvd1/

   -  mount:
        src: "/dev/cdrom"
        path: "/dvd1/"
        state: "mounted"
        fstype: "iso9660"

   - yum_repository:
        baseurl: "file:///dvd1/AppStream/"
        name: yum1
        description: dvd appstream
        gpgcheck: no

   - yum_repository:
        baseurl: "file:///dvd1/BaseOS/"
        name: yum2
        description: dvd baseos
        gpgcheck: no

   - package:
        name: "httpd"
        state: present

   - copy:
        dest: "/var/www/html/index.html"
        content: "WELCOME TO MY PAGE\n"

   - service:
        name: "httpd"
        state: started
        enabled: yes

   - firewalld:
        port: "80/tcp"
        state: enabled
        permanent: yes
        immediate: yes

   - yum_repository:
        name: docker-ce
        description: repository for docker
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        gpgcheck: no

   - package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

   - service:
        name: "docker"
        state: started
        enabled: yes

   - pip:
        name: "docker"
   - name: "creating folder"
     file:
          state: "directory"
          path: "/ansible"
   - copy:
       src: "/var/www/html/index.html"
       dest: "/ansible2/"
   - docker_image:
        name: "httpd"
        source: pull

   - docker_container:
        name: "myweb"
        image: "httpd"
        state: started
        exposed_ports:
        - "80"
        ports:
        - "7676:80"
        volumes:
        - "/ansible/:/usr/local/apache2/htdocs/"

   - firewalld:
        port: "7676/tcp"
        state: enabled
        permanent: yes
        immediate: yes

        #   - firewalld:
           #        port: "80/tcp"
        #        state: enabled
        #        permanent: yes
        #        immediate: yes
